version: "3.2" # https://docs.docker.com/compose/compose-file/compose-versioning/#version-3

services:
  kavita:
    image: kizaing/kavita:latest
    env_file: /var/data/config/kavita/kavita.env
    volumes:
      - /var/data/kavita:/kavita/config
    deploy:
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv1
        - traefik.frontend.rule=Host:kavita.example.com
        - traefik.port=8000     

        # traefikv2
        - "traefik.http.routers.kavita.rule=Host(`kavita.example.com`)"
        - "traefik.http.routers.kavita.entrypoints=https"
        - "traefik.http.services.kavita.loadbalancer.server.port=5000"           
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true