version: "3.2"

services:
  sonarr4k:
    image: lscr.io/linuxserver/sonarr:latest
    env_file: /var/data/config/sonarr4k/sonarr4k.env
    volumes:
      - /var/data/media/:/media
      - /var/data/sonarr4k:/config
    deploy:
      replicas: 1
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv1
        - traefik.frontend.rule=Host:sonarr4k.example.com
        - traefik.port=8989
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
        - traefik.frontend.auth.forward.trustForwardHeader=true        

        # traefikv2
        - "traefik.http.routers.sonarr4k.rule=Host(`sonarr4k.example.com`)"
        - "traefik.http.routers.sonarr4k.entrypoints=https"
        - "traefik.http.services.sonarr4k.loadbalancer.server.port=8989"
        - "traefik.http.routers.sonarr4k.middlewares=forward-auth"
        
    networks:
      - traefik_public
      - autopiratev2_public 

networks:
  traefik_public:
    external: true
  autopiratev2_public:
    external: true