version: "3.2"

services:
  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    env_file: /var/data/config/readarr/readarr.env
    volumes:
      - /var/data/media/:/books
      - /var/data/readarr:/config
    deploy:
      replicas: 1
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv1
        - traefik.frontend.rule=Host:readarr.example.com
        - traefik.port=8787
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
        - traefik.frontend.auth.forward.trustForwardHeader=true        

        # traefikv2
        - "traefik.http.routers.readarr.rule=Host(`readarr.example.com`)"
        - "traefik.http.routers.readarr.entrypoints=https"
        - "traefik.http.services.readarr.loadbalancer.server.port=8787"
        - "traefik.http.routers.readarr.middlewares=forward-auth"
    networks:
      - traefik_public
      - autopiratev2_public 

networks:
  traefik_public:
    external: true
  autopiratev2_public:
    external: true