version: '3'

services:
  app:
    image: advplyr/audiobookshelf
    env_file: /var/data/config/audiobookshelf/audiobookshelf.env
    volumes:
      - /var/data/audiobookshelf/config:/config
      - /var/data/audiobookshelf/metadata:/metadata
      # Set this next volume to wherever you store your audiobook library. 
      # You can define multiple libraries within this folder, like `/media/audio/podcasts`, `/media/audio/audiobooks`, etc
      - /var/data/media:/media
    deploy:
      replicas: 1      
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv1
        - traefik.frontend.rule=Host:audiobookshelf.example.com
        - traefik.port=80       

        # traefikv2
        - "traefik.http.routers.audiobookshelf.rule=Host(`audiobookshelf.example.com`)"
        - "traefik.http.routers.audiobookshelf.entrypoints=https"
        - "traefik.http.services.audiobookshelf.loadbalancer.server.port=80"

    networks:
      - traefik_public
      
networks:
  traefik_public:
    external: true
