version: "3.0"

services:
  plex:
    image: lscr.io/linuxserver/plex
    env_file: /var/data/config/plex/plex.env
    volumes:
      - /var/data/plex:/config
    deploy:
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv1
        - traefik.frontend.rule=Host:plex.example.com
        - traefik.port=32400

        # traefikv2
        - "traefik.http.routers.plex.rule=Host(`plex.example.com`)"
        - "traefik.http.routers.plex.entrypoints=https"
        - "traefik.http.services.plex.loadbalancer.server.port=32400"

    networks:
      - traefik_public
    ports:
      - 32469:32469
      - 32400:32400
      - 32401:32401
      - 3005:3005
      - 8324:8324
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp

networks:
  traefik_public:
    external: true