- name: Deploy docker stack
  import_role:
    name: docker-stack
  vars: 
    recipe: linx

- name: Create extra directories required
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - /var/data/linx
