- name: Deploy docker stack
  import_role:
    name: docker-stack
  vars: 
    recipe: joplin

- name: Create extra directories required
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - /var/data/joplin/database-dump
  - /var/data/runtime/joplin/database