version: '3'

services:

  db:
    image: mariadb:10
    env_file: /var/data/config/polr/polr.env
    networks:
      - internal
    volumes:
      - /var/data/runtime/polr/database:/var/lib/mysql

  app:
    image: carlonluca/polr
    env_file: /var/data/config/polr/polr.env
    deploy:
      replicas: 1
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv1
        - traefik.frontend.rule=Host:polr.example.com
        - traefik.port=8080    
        # - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        # - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
        # - traefik.frontend.auth.forward.trustForwardHeader=true        

        # traefikv2
        - "traefik.http.routers.polr.rule=Host(`polr.example.com`)"
        - "traefik.http.routers.polr.entrypoints=https"
        - "traefik.http.services.polr.loadbalancer.server.port=8080"
        # - "traefik.http.routers.polr.middlewares=forward-auth"
    networks:
      - internal
      - traefik_public

  db-backup:
    image: mariadb:10
    env_file: /var/data/config/polr/polr.env
    volumes:
      - /var/data/polr/database-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        mysqldump -h db --all-databases | gzip -c > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.sql.gz
        ls -tr /dump/dump_*.sql.gz | head -n -"$$BACKUP_NUM_KEEP" | xargs -r rm
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    networks:
      - internal

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.7.0/24
