- name: Deploy docker stack
  import_role:
    name: docker-stack
  vars: 
    recipe: huginn

- name: Create extra directories required
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - /var/data/huginn/database-dump
  - /var/data/runtime/huginn/database